### ISSUE TITLE
Only combination matrix saved when using ggsave()

### ISSUE THREAD

**Issue by z3tt** [const-ae/ggupset#28]
Hi @const-ae, thanks for the package! I realized that when one uses `ggsave()`, only the combination matrix is stored. 

```
library(ggplot2)
library(ggupset)

tidy_movies %>%
  distinct(title, year, length, .keep_all=TRUE) %>%
  ggplot(aes(x=Genres)) +
    geom_bar() +
    scale_x_upset(n_intersections = 20)
    
ggsave("test.pdf")
```

While it works with the usual device approach, it would be great to get `ggsave()` working. If it is for some reason not possible, I think adding a note and mentioning an approach how to save them correctly would be of great help for future users.

**Comment by const-ae** [comment]
Hi Cédric,

>  I realized that when one uses ggsave(), only the combination matrix is stored

yes, you are right. To save the complete plot you would have to say 

```{r}
pl <- tidy_movies %>%
  distinct(title, year, length, .keep_all=TRUE) %>%
  ggplot(aes(x=Genres)) +
    geom_bar() +
    scale_x_upset(n_intersections = 20)
    
ggsave("test.pdf", plot = pl)
``` 

The problem is that by default `ggsave` uses `plot = last_plot()`, which however then only points to combination matrix instead of the whole plot. I don't think there is much I can do to fix this from within the package, but I have added a paragraph to the [README](https://github.com/const-ae/ggupset#saving-plots) that explains how to save plots.

Best,
Constantin
