### ISSUE TITLE
Feature request: Include empty sets

### ISSUE THREAD

**Issue by maia-sh** [const-ae/ggupset#39]
I would like to include an **empty set** in an UpSet plot. I see #38 on the inclusion of **empty intersections**, but I've not managed to include an empty set.
Is this currently possible and if so how?
![upset-empty-set](https://github.com/const-ae/ggupset/assets/38968656/c2737bd6-b85f-4036-b29b-7685661e125d)

**Comment by const-ae** [comment]
Hi Maia,

this sounds like a reasonable feature. Unfortunately, I don't think I have implemented an option for it.

The problem is that I am specifically filtering out empty sets here https://github.com/const-ae/ggupset/blob/master/R/scale_upset.R#L192.

If I replace that line with `sets <- self$sets`, I can make the following plot:

![image](https://github.com/const-ae/ggupset/assets/5359014/fd2ee560-ac62-4595-b3ba-b0ebfdf61338)

However, I will not make this change, as I am not really actively working on this repo and don't know what kind of unintended consequences this change might have. Sorry.

Depending how much you want this feature, I recommend cloning this repo and making the change yourself.

Best,
Constantin

**Comment by const-ae** [comment]
This is the code I used to generate the plot, after changing line 192:

```R
  tidy_movies %>%
    distinct(title, year, length, .keep_all=TRUE) %>%
    ggplot(aes(x=Genres)) +
    geom_bar() +
    scale_x_upset(n_intersections = 20, sets = c("Comedy", "Action", "Empty set"))```
